version: '3.8'
services:
  booking-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 6000:80
    depends_on:
      - booking-backend
    networks:
      - booking-network
  booking-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    environment:
      NODEMAILER_AUTH_USER: 1824056030@qq.com
      NODEMAILER_AUTH_PASS: NODEMAILER_AUTH_PASS
      REDIS_SERVER_HOST: redis-container
      MYSQL_SERVER_HOST: mysql-container
    networks:
      - booking-network
  mysql-container:
    image: mysql
    volumes:
      - /Users/luyao/mysql-deploy-test:/var/lib/mysql
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 6001:3306
    networks:
      - booking-network
  redis-container:
    image: redis
    ports:
      - 6002:6379
    volumes:
      - /Users/luyao/redis-deploy-test-data:/data
    networks:
      - booking-network
networks:
  booking-network:
    driver: bridge
